[package]
name = "graylog"
version = "0.1.0"
authors = ["Pascal Friederich <paukul@gmail.com>"]

[dependencies]
clippy = "*"
log = "0.3"
flate2 = "0.2"
chrono = "0.2"
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"
byteorder = "0.5"

